/*
 *    MCreator note:
 *
 *    If you lock base mod element files, you can edit this file and the proxy files
 *    and they won't get overwritten. If you change your mod package or modid, you
 *    need to apply these changes to this file MANUALLY.
 *
 *
 *    Keep the SurvivalElements object in this class and all calls to this object
 *    INTACT in order to preserve functionality of mod elements generated by MCreator.
 *
 *    If you do not lock base mod element files in Workspace settings, this file
 *    will be REGENERATED on each build.
 *
 */
package net.mcreator.survival;

import net.fabricmc.fabric.api.block.FabricBlockSettings;
import net.minecraft.block.Block;
import net.minecraft.block.Material;
import net.minecraft.item.BlockItem;
import net.minecraft.item.ItemGroup;
import net.minecraft.util.registry.Registry;
import net.minecraft.util.Identifier;
import net.minecraft.item.Item;

import net.mcreator.survival.item.StoneRock;
import net.mcreator.survival.item.Saw;
import net.mcreator.survival.item.GrassVine;

import net.fabricmc.api.ModInitializer;

public class Survival implements ModInitializer {
	public static final Item StoneRock = new StoneRock();
	public static final Item GrassVine = new GrassVine();
	public static final Item Saw = new Saw();

	@Override
	public void onInitialize() {
		Registry.register(Registry.ITEM, new Identifier("survival", "stone_rock"), StoneRock);
		Registry.register(Registry.ITEM, new Identifier("survival", "grass_vine"), GrassVine);
		Registry.register(Registry.ITEM, new Identifier("survival", "saw"), Saw);
	}
}
